base_url = "http://localhost:1111"
title = "blog"
description = ""
theme = "duckquill"

default_language = "en"

compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
author = "kkky"

taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
	{ theme = "solarized-dark", filename = "syntax-theme-dark.css" },
	{ theme = "solarized-light", filename = "syntax-theme-light.css" }
]
smart_punctuation = true
bottom_footnotes = true

[search]
index_format = "fuse_json"

[languages.zh-Hans]
title = "blog"
description = ""
generate_feeds = true
build_search_index = true
taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[extra]
accent_color = "#3584e4"
accent_color_dark = "#ff7800"
show_copy_button = true
show_reading_time = true
show_share_button = false
show_backlinks = false

[extra.nav]
show_feed = true
show_theme_switcher = true
show_repo = false
links = [
	{ url = "@/blog/_index.md", name = "Blog" },
]

[extra.footer]
show_copyright = true
show_powered_by = true
show_source = false
links = [
	{ url = "@/blog/_index.md", name = "Blog" },
]
